main: "de.bypixeltv.skredis.Main"
name: "SkRedis"
version: "1.0.0"
api-version: "1.20"

author: "byPixelTV"
description: "A Skript-Addon to interact with Redis."
website: "https://bypixeltv.me"

libraries:
  - "dev.jorel:commandapi-bukkit-shade:9.4.0"
  - "dev.jorel:commandapi-bukkit-kotlin:9.4.0"
  - "net.axay:kspigot:1.20.3"

depend: [Skript]